sleep1x60:
	/bin/sh -c 'cd ../../build/native; ../../runit Sleep1x60'

sleep60x1:
	/bin/sh -c 'cd ../../build/native; ../../runit Sleep60x1'

file:
	mkdir ../../build/native/basedir
	/bin/sh -c 'cd ../../build/native; ../../runit File1'
	rmdir ../../build/native/basedir

